### ISSUE TITLE
Server adds a multiple ... without exceeding

### ISSUE THREAD

**Issue by dtikhonov** [martinduke/draft-duke-quic-load-balancers#4]
The draft states:

> When a server needs a new connection ID, it adds an arbitrary integer multiple of the divisor to its modulus, without exceeding the maximum integer value implied by the number of routing bits.

This almost makes it sound like one could run out of connection IDs.  I think this number can wrap.  More generally, the server is free to choose any valid value, not necessarily via addition.

**Comment by martinduke** [comment]
There is a finite number of connection IDs for a given server. It is approximately 
(2 ^ ((# of routing bits) + (# of non-routing bits))) / divisor 

A well designed configuration will pick values well enough to not have to recycle conn IDs too quickly.

routing bits = modulus + n * divisor, where n is chosen so that n >= 0 and (routing bits) < 2^(# of routing bits)

n is **definitely not** monotonically increasing. I'll try to figure out some clarifying language.
